/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

//Incluidos por el desarrollador 03/12/2024 16:50:52
#include "stdint.h"
#include "stdbool.h"
#include "Bsp.h"											//Prototipos y funciones inline para uso de timers STMx
#include "aurix_pin_mappings.h"				//Para uso de pines definidos mediante la aplicación PinMapper
#include "Ifx_Osci.h"									//Para uso de OneEye con un osciloscopio 10/12/2024 16:53:11
#include "SignalGenerator.h"					//Para uso del generador de señales

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define WAIT_TIME   		1                                	/* Wait time constant in milliseconds   */
#define SAMPLE_PERIOD   1e-3                              /* Sampling period in seconds                           */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
bool bled1_state;			//Si el led1 está activo, pin a LOW, bled1_state = true, al contrario false.

/* Oscilloscope object
 * The special Ifx_Osci type is recognised by OneEye as an oscilloscope object.
 */
Ifx_Osci g_osciDas;

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

/*********************************************************************************************************************/
/*-------------------------------------------------Functions--------------------------------------------------*/
/*********************************************************************************************************************/

void core0_main(void)
{

	Ifx_Osci_Config osciCfg;	//Configuración del osciloscopio 10/12/2024 18:18:46

	IfxCpu_enableInterrupts();
	
	/* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
	 * Enable the watchdogs and service them periodically if it is required
	 */
	IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
	IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
	
	/* Wait for CPU sync event */
	IfxCpu_emitEvent(&g_cpuSyncEvent);
	IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /* Initialize signals of the generator to be sampled by the oscilloscope */
    initSignals();
 
    /* Initialize the oscilloscope */
    Ifx_Osci_initConfig(&osciCfg);

    osciCfg.autoAddChannels = TRUE;                         /* When a signal is created, automatically assign the signal to a channel if there is a free one    */
    osciCfg.samplePeriod = SAMPLE_PERIOD;                   /* Sampling period of 1 ms                                                                          */
    osciCfg.triggerMode = Ifx_Osci_TriggerMode_automatic;   /* Oscilloscope mode after initialization (can be changed at runtime from OneEye)                   */

    /* Apply the configuration to the Oscilloscope */
    Ifx_Osci_init(&g_osciDas, &osciCfg);

    /* Add signals / variables  to be sampled */
    Ifx_Osci_addSignal(&g_osciDas, "Signal A", Ifx_Osci_DataType_Float32, &g_signalGenerator.output.signalA, 0);
    Ifx_Osci_addSignal(&g_osciDas, "Signal B", Ifx_Osci_DataType_SInt32, &g_signalGenerator.output.signalB, 0);

	gpio_init_pins();	//El pin LED1_GREEN se inicia aLOW. Led encendido.    
  bled1_state = true;  
	/* Initialize a time variable to enable sampling every 1ms */
	Ifx_TickTime ticksFor1ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);
	
	/* Get a timestamp for 1ms in future */
	Ifx_TickTime deadline = getDeadLine(ticksFor1ms);
	while(1)
	{
		if (isDeadLine(deadline))
		{
		  /* This code is executed every 1 ms */
		
		  /* Update the next deadline for sampling */
		  deadline = addTTime(deadline, ticksFor1ms);
		
		  /* Update signal value */
		  computeSignals();
			if (g_signalGenerator.output.signalA == 0.0)
			{
				bled1_state = !bled1_state;
				IfxPort_togglePin(IFXCFG_PORT_LED1_GREEN.port, IFXCFG_PORT_LED1_GREEN.pinIndex);
			}
		  /* Sample signals */
		  Ifx_Osci_step(&g_osciDas);
		}
	}
}
