/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title ADC single channel conversion
 * \abstract The Enhanced Versatile Analog-to-Digital Converter (EVADC) is configured to measure an analog signal using queued request.
 * \description An analog input channel is continuously converted using the queued mode.
 *              The input value is determined by the potentiometer on the board.
 *              Two LEDs are used to indicate a voltage interval. Thus depending on the conversion
 *              value, one or both LEDs are on.
 *
 * \name ADC_Single_Channel_1_KIT_TC375_LK
 * \version V1.0.1
 * \board AURIX TC375 lite Kit, KIT_A2G_TC375_LITE, TC37xTP_A-Step
 * \keywords ADC, ADC_Single_Channel_1, EVADC, conversion, single channel scan, AURIX
 * \documents https://www.infineon.com/aurix-expert-training/Infineon-AURIX_ADC_Single_Channel_1_KIT_TC375_LK-TR-v01_00_01-EN.pdf
 * \documents https://www.infineon.com/aurix-expert-training/TC37A_iLLD_UM_1_0_1_12_1.chm
 * \lastUpdated 2021-06-29
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "aurix_pin_mappings.h"		//Para uso de pines definidos mediante la aplicación PinMapper

//Incluidos por el desarrollador 13/01/2025 18:14:02
#include "stdint.h"								//For Integer Types use 
#include "stdbool.h"							//For Boolean type and values use
#include "constants.h"						//Contains the common defines of the application

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

void core0_main(void)
{
	uint32 u32count = CERO_U32;			//Contador de iteraciones
#define CONV_COUNT_U32	10000000UL
	
	IfxCpu_enableInterrupts();
	
	/* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
	 * Enable the watchdogs and service them periodically if it is required
	 */
	IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
	IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
	
	/* Wait for CPU sync event */
	IfxCpu_emitEvent(&g_cpuSyncEvent);
	IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
	
	IfxPort_setPinHigh(IFXCFG_PORT_M_LED1_GREEN.port, IFXCFG_PORT_M_LED1_GREEN.pinIndex);		//Ponemos los pines a HIGH, desactivos,
	IfxPort_setPinHigh(IFXCFG_PORT_M_LED2_GREEN.port, IFXCFG_PORT_M_LED2_GREEN.pinIndex);		//antes de ponerlos en modo salida

	gpio_init_pins();

// Activamos para comprobar 14/01/2025 16:44:56
//	IfxPort_setPinLow(IFXCFG_PORT_M_LED1_GREEN.port, IFXCFG_PORT_M_LED1_GREEN.pinIndex);
//	IfxPort_setPinLow(IFXCFG_PORT_M_LED2_GREEN.port, IFXCFG_PORT_M_LED2_GREEN.pinIndex);
	
	
	// Bucle infinito
	while(true){
		u32count++;
		if (CONV_COUNT_U32 <= u32count){
			u32count = CERO_U32;
			IfxPort_togglePin(IFXCFG_PORT_M_LED1_GREEN.port, IFXCFG_PORT_M_LED1_GREEN.pinIndex);
			IfxPort_togglePin(IFXCFG_PORT_M_LED2_GREEN.port, IFXCFG_PORT_M_LED2_GREEN.pinIndex);
		}//(CONV_COUNT_U32 <= u32count)	
	}//(true)
}
